name: Compile PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      # https://github.com/marketplace/actions/latex-compilation
      - name: LaTeX compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          # The root LaTeX file to be compiled
          root_file: codecheck-paper.tex
          # The working directory for the latex compiler to be invoked
          #working_directory: # optional
          # LaTeX engine to be used
          #compiler: # optional, default is latexmk
          # Extra arguments to be passed to the latex compiler
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          # Install extra packages by apt-get
          #extra_system_packages: # optional
      
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: codecheck-paper
          path: codecheck-paper.pdf
