name: Compile PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Pull image
        run: docker pull rocker/verse:4.0.3
      
      - name: Build image
        run: |
           docker build --tag codecheckpaper .

      - name: Render PDF
        run: |
           docker run --rm -i -v $(pwd):/paper codecheckpaper R -q -e 'setwd("/paper"); tinytex::latexmk("codecheck-paper.tex", engine="xelatex")'

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: codecheck-paper
          path: codecheck-paper.pdf
